### PR TITLE
more webhooks and some webapi

### PR DESCRIPTION
**Pull request by nazoking**
Added some webhook events.

 * [pull_request](https://developer.github.com/v3/activity/events/types/#pullrequestevent) open, closed(merged), reopen
 * [issues](https://developer.github.com/v3/activity/events/types/#issuesevent) open, closed, reopen
 * [issue_comment](https://developer.github.com/v3/activity/events/types/#issuecommentevent) created

(Not implementd pull_request synchronized action yet)

And "X-Github-Event" header on web hook request.

And some GitHub-WebAPI/v3.

 * [Users](https://developer.github.com/v3/users/) get-a-single-user
 * [Issues/Comments](https://developer.github.com/v3/issues/comments/) list-comments-on-an-issue, create-a-comment
 * [Pull Requests](https://developer.github.com/v3/pulls/) list-pull-request, get-a-single-pull-request, list-commits-on-a-pull-request
 * [Repositories](https://developer.github.com/v3/repos/) get

( but Authorizations is not implemented yet)

I want to use jenkins plugin '[github pull request builder](https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin)'.
Final goal is to implement the features that are used in that plugin ( #545 ).

### CODE REVIEW

**Comment by takezoe** [comment]
@tanacasino This request helps your work?

**Comment by tanacasino** [comment]
It's good!

**Comment by nazoking** [comment]
@takezoe @tanacasino Thank you for interest to this pull request.

I Implemented commit status api based on this branch. https://github.com/team-lab/gitbucket/tree/feature/add-commit-status-api
  * create/update api and record to DB ( new table )
  * show status on pull_request page.

Can i merge `feature/add-commit-status-api` into `feature/more-webhooks-and-some-webapi` ( and pr #610 ... ) ? 

And can I create code to continue the work of this?

my next plan is...

 * create merged result branch `pull/{issueId}/merge`
 * Implement mergeable status cache to DB
   * add columns on pull_request table ..?
   * set api parameter.
 * Implement more web-hook
   * pull_request syncronized

or you direction me to refactoring?

 * I think WebHookService is too big ..  sub-classes for api should move to other class or new package ( but i dose not found package naming policy.. ).
 * I think  notifications ( send mails, post web-hooks, update activities, and check mergeablity ) moves to other thread like actor ( but GitBucket dose not have actorSystem ).

or I wait for merge this pull_request?

or you continue it?

**Comment by tanacasino** [comment]
@nazoking いつもありがとうございます。レスポンス悪くてすいません。
こちらマージを予定して検討させていただいています。

本流へのマージについてですが、#545 に書いて頂いた通り、JenkinsのGitHub PullRequest Builder Pluginと合わせて動くが出来る状態になったらマージしたいと考えています。

ですのでお手数ですが、api-supportというブランチを作成しますので、そちらにPullRequestを送り直してもらうことは可能でしょうか？
こちらに #610 や commit status APIなどの変更を取り入れていき、開発・動作確認を進めたいと考えています。

**Comment by nazoking** [comment]
merged #635

**Pull request closed without merging**
