### PR TITLE
add export functionality via system settings page and via URL, close …

### PR DESCRIPTION
**Pull request by McFoggy**
Hi,

find enclosed a small contribution to gitbucket.
It consists in providing a way to export the HSQLDB database. Such a functionality allows then setup some backup mechanisms for gitbucket.

I provide currently 2 ways to backup the database:

1. via the System Administration GUI / System Settings : a new panel is added for database export
image
1. via an HTTP GET on http://server:port/export

PS: I am totally new to scala world (pure java/jee developper) so by advance I apologize if I didn't respected some scala conventions.

### CODE REVIEW

**Comment by McFoggy** [comment]
I was thinking in changing the command URL from `/export` to `/database/backup`

**Comment by aidanhs** [comment]
Possibly should be `adminOnly`?

**Comment by McFoggy** [comment]
@aidanhs it could be but only when there will be an official support of basic authentication so that command lines tools (curl, wget, ...) could authenticate . Not sure it is currently the case.

**Comment by McFoggy** [comment]
@takezoe do you want this PR to be provided instead as a plugin or do you plan to integrate it in some version?

**Comment by takezoe** [comment]
We've started MySQL support, so I think we should add export and import feature which does not depend on the kind of the database.

**Comment by takezoe** [comment]
However it will be useful if this export functionality is provided as a plugin.

**Comment by McFoggy** [comment]
I have created [gitbucket-h2-backup-plugin](https://github.com/McFoggy/gitbucket-h2-backup-plugin) to integrate the H2 backup feature of this PR.

I have tested on 3.6 version, it works as expected.

If you agree I'll close this PR.

**Comment by takezoe** [comment]
@McFoggy Thanks a lot. I agree to close this pull request. gitbucket-h2-backup-plugin is great job!

**Comment by McFoggy** [comment]
Closed in favor of plugin [gitbucket-h2-backup-plugin](https://github.com/McFoggy/gitbucket-h2-backup-plugin) usage.

@takezoe please also close issue #575

**Pull request closed without merging**
