### PR TITLE
Improve searching with Lucene

### PR DESCRIPTION
**Pull request by nus**
Improve speed of the searching with Lucene.

Note that it is slow to search when the first time searching or after the repository was modified because the processing contains indexing.

The index data will store in `$GITBUCKET_HOME/tmp/_index` directory.

### CODE REVIEW

**Comment by dkowis** [comment]
:+1: Searching is pretty terrible with a repo with lots of files. 

Could it perhaps update the index on a push?

**Comment by nus** [comment]
How can I fix this failed?
Only push with any changes?

**Comment by takezoe** [comment]
We are planning embedded Elasticsearch integration for full-text search.

**Comment by nus** [comment]
@takezoe
I am looking forward to the full-text search!

**Pull request closed without merging**
