### PR TITLE
(Optional) AsciiDoc Renderer

### PR DESCRIPTION
**Pull request by lefou**
This PR enabled support for the AsciiDoc markup language. The renderer is based on Asciidoctor and the AsciidoctorJ project, which provides a Java API for the Ruby/JRuby based rendering engine. Unfortunately the required jruby runtime add lots of dependencies to the project (only four, but jruby-complete is about 22MB large). As this size is considered too large by @takezoe (see #288), this PR only provides the support but not the dependencies.

At runtime (or to be exact at initalization time) the renderer tries to load some required classes. If they are not found, the Asciidoc renderer will be disabled.

To enable the renderer, the GitBucket operator need to provided the following dependencies:

- org.asciidoctor:asciidoctorj:1.5.2
- org.jruby:jruby-complete:1.7.16.1
- org.slf4j:slf4j-api:1.7.7
- net.sourceforge.htmlcleaner:htmlcleaner:2.10

Other versions may work as well.

This PR is based on my Asciidoc branch, which I maintain since the support was removed from GitBucket (see #288). It runs without any hassle on at least two installations. The refactorings to make it optional are fairly new though.

### CODE REVIEW

**Comment by lefou** [comment]
Could anyone please comment on this PR! It's almost a half year old now and nobody looked at it. It adds functionality of GitHub, so it is in the scope of a pure GitHub "clone". Also it adds no additional dependencies if the featrue is not required.

**Comment by aadrian** [comment]
I think such functionality should be in the form of a GitBucket **plug-in**. 
This way the **users** can opt for it or not from the GUI, not the developers, and it adds no build/configuration/setup complications.

**Comment by lefou** [comment]
Fair enough. I could provide a plug-in that just adds the required dependencies. As a result, the feature would be enable-able by the user.

**This feature is ready to use since one and a half year!** And yet, we don't have the required extension point in the plug-in system, but you keep telling me to implement it as plug-in. Why not go with the solution of this PR until we get the plug-in functionality, and migrate the code into a plug-in as soon as the plug-in system is capable of.

What I'm completely missing in this discussion: Are you at all interested in that feature?

Please don't take it as offence, really. I just need to know if it's worth to spend my energy any longer.

**Comment by aadrian** [comment]
> And yet, we don't have the required extension point in the plug-in system. 

I think this is because the extension API is not pre-designed, but driven by requirements and pull requests since it's a very complicated stuff that could easily lead to broken performance or security issues. It could also make everything very complicated if it were pre-designed, accounting for all possible extension situations.

> Are you at all interested in that feature?

As a GitBucket user with quite a few installations: I am.

However I could not deploy it on all installations I'm supporting. A plug-in solution would be ideal in this case too, and if the users decide later based on a demo that they want it, than they could simply add it with a few clicks (without me redeploying everything).

GitBucket is fantastic, but let's face it: there are many requirements (some of them even contradict the purpose of the project), and the development team can't possible implement all of them, so an improved extensibility an some sort of TCK suite would mitigate this.

**Comment by lefou** [comment]
Thanks for your point of view. 

So, are you open for any "intermediate" solution, e.g. providing the dependencies via plug-in (as far as I know, the new plug-in system can add dependencies) but have the logic in the core (this PR)? If yes, I could try to create such a plug-in and could also do some manual tests. I can't see any negative impact for users who don't need that feature.

**Comment by lefou** [comment]
For reference: #428

**Comment by aadrian** [comment]
> So, are you open for any "intermediate" solution, e.g. providing the dependencies via plug-in but have the logic in the core (this PR)

Yes. 
However the next task of completely moving the code to plug-in and adding more API extension points, needs to be done quite soon too.

**Comment by hansgru** [comment]
+1 for an AsciiDoc GitBucket Plug-in :).

**Comment by lefou** [comment]
Great. I'll create an "enabler" plug-in and report back. If it works as expected, this PR needs to be merged though.

**Comment by aadrian** [comment]
@lefou Is there an official repository for GitBucket plug-ins? I could not find any :(.

**Comment by lefou** [comment]
Sorry, I don't know. The only plug-in I'm aware of is https://github.com/takezoe/gitbucket-gist-plugin. And the release announcement of GitBucket 3.0 said the self-built plug-in needs to be copied into the GitBucket installation folder. :-(

Unfortunately, I couldn't find any documentation about the new (2nd) plug-in system either, so I'm stuck. Meanwhile, I asked @takezoe via Gitter... so hopefully after his reply I'm wiser. ;-)

**Comment by takezoe** [comment]
@lefou I started to add new extension point to add markup renders such as Asciidoc. It will be available in the next release. However plug-in system and API is still unstable. We are struggling for it. So I can't say about it clearly now.

**Comment by lefou** [comment]
@takezoe Wow, your latest additions as part of https://github.com/takezoe/gitbucket/issues/775 (`Renderer`, `RenderRequest`, ...) looks a lot like the code in this PR. Was it really such a huge problem to use this PR or to ask me to do the adaptations. I would have liked to also extend and contribute to the plug-in API, but you told me to wait more than once. I'm happy the functionality is finally there but I'm also a bit less motivated to contribute again.

**Comment by lefou** [comment]
Closing, since it can be implemented as plug-in.

**Comment by lefou** [comment]
No reaction? Too bad.

**Comment by takezoe** [comment]
@lefou Sorry for my slow reply. Is not the current plugin API enough to implement the asciidoc render as a plugin? If it's so, I wish to improve API. Of course your PR to make it is welcome now!

**Comment by lefou** [comment]
@takezoe I think the current API is enough to implement the plug-in. But, you missed my point (https://github.com/takezoe/gitbucket/pull/616#issuecomment-109874984). I was questioning the way the new API got in. No comment, no merge, but it looked a lot like a copy and paste of this PR. After all, no big deal and I'm glad the API is finally there, but the process was definitely not what I was expecting from an OSS project. Especially, after I have invested so much.

Never mind, I guess I will write this plug-in someday.

**Comment by takezoe** [comment]
@lefou It was my mistake on OSS project. However I want to integrate render API in 3.4 because you are waiting long time. Therefore I took from code from this PR. I also thought it helps move your plugin to the plugin.

This is your work expressly. Thanks for your contribution!

**Comment by lefou** [comment]
So, finally, after calming down I created https://github.com/lefou/gitbucket-asciidoctor-plugin.

**Pull request closed without merging**
